
import { UnitData, UnitStatus, Sector } from './types';

export const SECTORS: Sector[] = [
  'SECTOR 1A', 'SECTOR 1B',
  'SECTOR 2A', 'SECTOR 2B',
  'SECTOR 3', 'SECTOR 4',
  'SECTOR 5', 'SECTOR 6',
  'SECTOR 7', 'SECTOR 8',
  'SECTOR 9A', 'SECTOR 9B',
  'RESCATE',
  'GIR'
];

export const FUEL_TYPES = ['GLP', 'GASOLINA'];

export const INDICATIVES = [
  'CHOFER', 'JEFE AREA', 'MOTORIZADO', 'PNP', 'SERENO', 'SUPERVISOR', 'FISCALIZACION', 'TRANSITO', 'RESCATE', 'DESCANSO COMPENSATORIO', 'FALTO', 'DESCANSO MEDICO', 'ONOMASTICO', 'PERMISO'
];

export const VEHICLES = [
  { id: 'M-13', plate: 'EUJ-821' },
  { id: 'M-14', plate: 'FGH-102' },
  { id: 'M-15', plate: 'ABC-123' },
  { id: 'M-16', plate: 'XYZ-987' },
  { id: 'M-17', plate: 'PLQ-456' },
  { id: 'M-18', plate: 'TRX-112' },
  { id: 'M-19', plate: 'VBN-334' },
  { id: 'M-20', plate: 'KJH-556' },
  { id: 'M-21', plate: 'LKO-998' },
  { id: 'L-15', plate: 'HON-452' },
  { id: 'L-16', plate: 'YAM-789' },
  { id: 'L-17', plate: 'KWA-001' },
  { id: 'L-18', plate: 'SUZ-222' },
  { id: 'L-19', plate: 'YAM-554' },
  { id: 'L-20', plate: 'HON-112' },
  { id: 'L-21', plate: 'KWA-223' },
  { id: 'P-01', plate: 'PE-1001' },
  { id: 'P-02', plate: 'PE-1093' },
  { id: 'P-03', plate: 'PE-2022' },
  { id: 'P-04', plate: 'PE-3033' },
  { id: 'P-05', plate: 'PE-4044' },
  { id: 'P-06', plate: 'PE-5055' },
  { id: 'P-07', plate: 'PE-6066' },
  { id: 'P-08', plate: 'PE-7077' }
];

export const RADIOS: string[] = [];

export const PERSONNEL_NAMES = [
  'Villanueva Villafani, Joe',
  'Insp. Mendoza, Ricardo',
  'SOT. Garcia, Juan',
  'Caja Quiroz, Carlos',
  'Ramos L., Hugo',
  'Torres Ruiz, Manuel',
  'Soto Mayor, Luis',
  'López Vega, Ricardo',
  'Castro P., Elena',
  'García Salas, Pedro',
  'Vargas J., Mario',
  'Vidal Hipolito, J.',
  'Paredes C., Alberto',
  'Mendoza T., Franco',
  'Huamaní R., S.',
  'Quispe M., Jhon',
  'Gomez Chavez, R.',
  'Salazar F., Ana',
  'Beltrán O., Jorge',
  'Villalobos K., M.',
  'Cárdenas H., Raúl',
  'Sánchez M., Lucía',
  'SOT. Ramirez, Victor',
  'Cap. Espinoza, Maria',
  'Alvarez P., Roberto',
  'Caceres G., Fernando',
  'Dávila M., Sonia',
  'Espichán R., Luis'
];

export const INITIAL_UNITS: UnitData[] = [
  // --- CHOFERES (PATRULLAS) ---
  {
    id: 'M-13',
    type: 'CHOFER',
    personnel1: '',
    personnel2: '',
    plate: 'EUJ-821',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '07:00 - 19:00',
    fuel: 'GLP / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'M-14',
    type: 'CHOFER',
    personnel1: '',
    personnel2: '',
    plate: 'FGH-102',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '07:00 - 19:00',
    fuel: 'GLP / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'M-15',
    type: 'CHOFER',
    personnel1: '',
    plate: 'ABC-123',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '07:00 - 19:00',
    fuel: 'GLP / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'M-16',
    type: 'CHOFER',
    personnel1: '',
    plate: 'XYZ-987',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '07:00 - 19:00',
    fuel: 'GLP / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'M-17',
    type: 'CHOFER',
    personnel1: '',
    plate: 'PLQ-456',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '07:00 - 19:00',
    fuel: 'GLP / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'M-18',
    type: 'CHOFER',
    personnel1: '',
    plate: 'TRX-112',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '07:00 - 19:00',
    fuel: 'GLP / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'M-19',
    type: 'CHOFER',
    personnel1: '',
    plate: 'VBN-334',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '07:00 - 19:00',
    fuel: 'GLP / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'M-20',
    type: 'CHOFER',
    personnel1: '',
    plate: 'KJH-556',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '07:00 - 19:00',
    fuel: 'GLP / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'M-21',
    type: 'CHOFER',
    personnel1: '',
    plate: 'LKO-998',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '07:00 - 19:00',
    fuel: 'GLP / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  // --- MOTORIZADOS ---
  {
    id: 'L-15',
    type: 'MOTO',
    personnel1: '',
    plate: 'HON-452',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '07:00 - 19:00',
    fuel: 'GLP / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'L-16',
    type: 'MOTO',
    personnel1: '',
    plate: 'YAM-789',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '07:00 - 19:00',
    fuel: 'GLP / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'L-17',
    type: 'MOTO',
    personnel1: '',
    plate: 'KWA-001',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '07:00 - 19:00',
    fuel: 'GLP / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'L-18',
    type: 'MOTO',
    personnel1: '',
    plate: 'SUZ-222',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '07:00 - 19:00',
    fuel: 'GLP / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'L-19',
    type: 'MOTO',
    personnel1: '',
    plate: 'YAM-554',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '07:00 - 19:00',
    fuel: 'GLP / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'L-20',
    type: 'MOTO',
    personnel1: '',
    plate: 'HON-112',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '07:00 - 19:00',
    fuel: 'GLP / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'L-21',
    type: 'MOTO',
    personnel1: '',
    plate: 'KWA-223',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '07:00 - 19:00',
    fuel: 'GLP / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  // --- SERENOS ---
  {
    id: 'P-01',
    type: 'SERENO',
    personnel1: '',
    plate: 'PE-1001',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '08:00 - 20:00',
    fuel: 'N/A / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'P-02',
    type: 'SERENO',
    personnel1: '',
    plate: 'PE-1093',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '08:00 - 20:00',
    fuel: 'N/A / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'P-03',
    type: 'SERENO',
    personnel1: '',
    plate: 'PE-2022',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '08:00 - 20:00',
    fuel: 'N/A / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'P-04',
    type: 'SERENO',
    personnel1: '',
    plate: 'PE-3033',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '08:00 - 20:00',
    fuel: 'N/A / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'P-05',
    type: 'SERENO',
    personnel1: '',
    plate: 'PE-4044',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '08:00 - 20:00',
    fuel: 'N/A / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'P-06',
    type: 'SERENO',
    personnel1: '',
    plate: 'PE-5055',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '08:00 - 20:00',
    fuel: 'N/A / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'P-07',
    type: 'SERENO',
    personnel1: '',
    plate: 'PE-6066',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '08:00 - 20:00',
    fuel: 'N/A / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  },
  {
    id: 'P-08',
    type: 'SERENO',
    personnel1: '',
    plate: 'PE-7077',
    indicative: '',
    radio: '',
    status: UnitStatus.PATRULLANDO,
    reason: '',
    km: '0 / 0 / 0 / 0',
    hours: '08:00 - 20:00',
    fuel: 'N/A / 0',
    expense: 'S/ 0.00',
    parts: '0',
    quadrant: '',
    mechanics: 'Operativo',
  }
];

// Sector-specific data mapping
// Sector-specific data mapping - Now empty to force usage of default INITIAL_UNITS or fetched data
export const SECTOR_DATA: Record<Sector, UnitData[]> = {
  'SECTOR 1A': INITIAL_UNITS,
  'SECTOR 1B': [],
  'SECTOR 2A': [],
  'SECTOR 2B': [],
  'SECTOR 3': [],
  'SECTOR 4': [],
  'SECTOR 5': [],
  'SECTOR 6': [],
  'SECTOR 7': [],
  'SECTOR 8': [],
  'SECTOR 9A': [],
  'SECTOR 9B': [],
  'RESCATE': [],
  'GIR': [],
};

